version: "1.0.0"

name: React
description: |
  This will install some stuff and scaffold react project for create-react-app.
files:
  - path: .eslintrc.js
    strategy: skip-if-exists
    destination: tmp/.eslintrc.js
      
  - path: package.json
    strategy: merge
    destination: tmp/package.json

  - path: .jsconfig.json
    strategy: merge
    destination: tmp/.jsconfig.json
